### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by MrManny** [plasticrake/hs100-api#1]
When I try to use your example in my local node v5.12.0 instance running on Gentoo Linux, I get the following error:

```js
/home/manny/hs110q/node_modules/hs100-api/index.js:16
function Hs100Api (config = {}) {
                          ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/manny/hs110q/index.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

The example I used was:
```js
'use strict';

const Hs100Api = require('hs100-api');
const hs = new Hs100Api({host: '192.168.0.11'});
hs.getSysInfo().then(console.log);
```

**Comment by plasticrake** [comment]
Ah yes, this is syntax that requires Node 6. I'll update the package.json to show this dependency. Are you able to use Node 6? It wouldn't take long to make it compatible with 5 if anybody needs it.

**Comment by MrManny** [comment]
Ah, I was just confused because the package.json declared Node v5. Even with syntactic changes, it would at very least require 5.10.0 (because that's where Buffer things you are using were introduced).

No need to necessarily change the syntax, I just forked it and applied the changes as I needed them. Also made the Api into an ES6 class since I find XYZ.prototype.myfunction just too verbose.

If you want to, feel free to merge the changes. Otherwise, I would recommend changing package.json to declare Node 6 as the required engine.

**Comment by MrManny** [comment]
Ah, I just noticed you did change the package.json. Very well :) I guess this is resolved then.

**Comment by plasticrake** [comment]
If you want to make a pull request I'd consider it. I just added semistandard to the project as well, just make sure the style matches, I noticed lot of formatting changing in the diff.

**Comment by MrManny** [comment]
Ah yes, sorry about that. Webstorms *really* loves 4-spaces indentation.
I'll create a branch for the pull request, switch it to 2-spaces indentation, and merge your recent commits. And if you want to avoid having 4-spaces indentation in your history for a little while, I'll see if I can squash it. But it will take a day or two until I can get to it.

**Comment by bartdorsey** [comment]
It's great that you made this and figured it out, however most people running homebridge are using the stable version of node (v4). In particular I can't use the homebridge-hs100 without going to node (v5) at least, but then a bunch of my other homebridge plugins break.  :(  I don't know if there's a solution to this problem (except for waiting for the entire homebridge community to move to node v5.....)

**Comment by plasticrake** [comment]
Thanks for your input @bartdorsey. I've made changes to be compatible for node v4 (tested using 4.4.7)
