### ISSUE TITLE
Trying to use this repository on scriptr.io, but receiving syntax error in plug.js when attempting to import it

### ISSUE THREAD

**Issue by caffeinatedMike** [plasticrake/hs100-api#5]
I'm trying create a personal api for my home automation that includes this api, but I'm having trouble getting it setup. I'm using [Scriptr.io](Scriptr.io) and they have a setting that allows you to install a module directly from my github. When I do this I receive two errors:

```
error: modules/tplink/client.js missing ; before statement (modules/tplink/client.js#14)
error: modules/tplink/plug.js syntax error (modules/tplink/plug.js#23)
```

the utils.js file seems to import fine, but client.js & plug.js don't due to the above errors. I have not changed any code since forking the project off of you. What could I be doing wrong?

**Comment by plasticrake** [comment]
I'm not familiar with Scriptr.io, but what versions of node is the code running on? Also your repo is in violation of the license by removing the LICENSE file.

**Comment by caffeinatedMike** [comment]
Sorry about that, didn't mean to violate anything. I only removed it because I tried to import the modules it gave an error with those other docs. I've deleted my repository and re-forked so that the licensing information is there again. Again, didn't mean any disrespect. I'm not sure how to answer your question about version of node.js. All I know is scriptr.io code is javascript. Maybe I have to import some library?

**Comment by plasticrake** [comment]
No worries about the LICENSE. I took a quick look at the Scriptr.io documentation and they don't mention Node at all. They may be using a proprietary JS engine, and one that doesn't support the Class syntax added with ES2015. You are welcome to try rewriting to use the older syntax, or asking Scriptr to add support for this.

**Comment by caffeinatedMike** [comment]
I'm not really sure how the two differ, how would I modify the bits that use the class syntax in order for the older proprietary JS engine to support the code? Could you give me an example that I could possibly get an idea from please?

**Comment by caffeinatedMike** [comment]
Ok, so I was able to convert everything. The last issue seems to be the lack of the dgram library in the proprietary JS engine. Is there perhaps an alternative library that normal JS has?

**Comment by plasticrake** [comment]
I really don't think scriptr.io is going to work out for this. This hs100-api requires to be running on your local LAN. And whatever server scriptr.io is running won't be able to contact the hs100 devices. I don't even see any info on opening a socket using scriptr.io.

**Comment by caffeinatedMike** [comment]
Oh, bummer :/ I'll have to try and figure out another way then. Ideally I'd
like to create a personal api online and open up the port on my router (I
know, security risk) if that's what it would take to be able to use the api
somehow. I'm guessing the way you created it is meant be run off a server
or RaspPi?

**Comment by plasticrake** [comment]
Correct, its meant to be running on a Node server.
